### ISSUE TITLE
Contact Page is a Blank Page in the Frontend

### ISSUE THREAD

**Issue by ghost** [mecha-cms/extend.plugin.contact#1]
Hi @tovic,

unfortunately a blank page with the contact form is displayed. This is with me under https://mechacms.wpzweinull.ch/kontakt.

I have added to this page in the editor in the backend.

    [‌[‌contact‌]‌]

    [‌[‌contact kick="http://localhost/thank-you"‌]‌]

What can be wrong or what is wrong?

The extensions `page` and `block` I have updated.

Thanks in advance.

P.S. I also updated Genome files

**Comment by taufik-nurrohman** [comment]
Sorry but I can&rsquo;t reproduce the bug. See example &rarr; http://latitudu.tk/contact

**Comment by ghost** [comment]
With the Contact-Plugin I did not go any further. Everything tried. The page is created in the markdown and HTML. Then I entered directly into kontakt.page the code. Everything did not help.

Strangely, the blank page is always displayed in the front-end. It is certainly something, but what exactly, I do not know yet.

**Comment by taufik-nurrohman** [comment]
Have you tried in another page, for example in the home page?

**Comment by ghost** [comment]
Now I am a step further and have installed the Genome Branch at https://mechacms.liebrecht-projekte.de . The contact form is displayed under https://mechacms.liebrecht-projekte.de/contact .

On Wpzweinull.ch I have in the root of all hand WP plugins like AntiSpam, AntiContactSpam and Wordfence as protection for the domain. Therefore, it is very likely that any contact forms across the domain will be prevented.

But this does not apply to the Wordpress blog on https://wpzweinull.ch . There everything works.

On the subdomain https://mechacms.wpzweinull.ch will work without the contact form.

And on the new Mecha website I gather more experiences: smilie:

This issue you can now close, I guess.
